# Site settings
title: Brendan Billingsley
email: billingb@gmail.com
description: >
  Billingsley Custom Software LLC landing page
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "https://billingb.github.io/" # the base hostname & protocol for your site
twitter_username: brendanbill
github_username:  billingb
linkedin_id: brendan-billingsley-3894bb4

# Build settings
# markdown: kramdown
